version: '3'

services:
  aethonex-com:
    image: aethonex-com
    container_name: aethonex-com
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=aethonex.com  
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=aethonex.com
      - LETSENCRYPT_EMAIL=reshetovdenis@gmail.com
      
networks:
  default:
    external:
      name: nginx-proxy