version: '3'

services:
  ui-slonigiraf-org:
    image: aethonex-com
    container_name: aethonex-com
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=aethonex.com  
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=aethonex.com
      - LETSENCRYPT_EMAIL=reshetovdenis@gmail.com
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy